#######################
### RUN THIS SCRIPT ###
#######################
###     SECOND      ###
#######################

### This script contains all the references used in the modeling process. These references might change as new survey periods are added, or names (like subpopulation, indicator, etc.) are changed.
### This script also relies on there being a separate reference Excel file stored in the Reference folder within the R Project working directory. The sheet names and column names of this file
### must be kept the same as the code references it by exact name matching.


#/////////////////////////////////#
#     DEFINING TIME PERIODS       #
#/////////////////////////////////#
T0 <- "WSA/EMAP West 2000-2004"
T1 <- "NRSA 2008-2009"
T2 <- "NRSA 2013-2014"

tvt <- c("T1vT2", "T0vT2", "T0vT1")
front <- c("Count.NResp", "Estimate.P", "Estimate.U")

# List of all columns needing imputing is generated by a function called imputecollist, defined in the Functions script.
# Make sure Functions script is run before creating these lists

# list_status <- as.character()
# list_status <- imputecollist(front, "T2", "Status", "Condition")
# 
# list_diff <- as.character()
# list_diff <- imputecollist(front, "Diff", tvt, "Condition")
# list_diff <- list_diff[-c(grep("Count.NResp", list_diff))] # Removing Count.NResp as the .Diff columns are not included in the raw data
# 
# list_change <- as.character()
# list_change <- imputecollist(front, "", tvt, "Condition")
# 
# list_sig <- as.character()
# list_sig <- imputecollist("Sig95.Flag", "Diff", tvt, "Condition")
# list_sig <- list_sig[-c(grep("NA", list_sig))]


#///////////////////////////#
#     LISTS FOR NAMES       #
#///////////////////////////#

names_pl <- c("TypePlainLanguage", "SubpopulationPlainLanguage")
names_raw <- c("Type", "Subpopulation")
names_other <- c("Category", "MetricCategory", "CategoryConditionPlainLanguage", "CategoryConditionMostDisturbed", "Indicator", "IndicatorPlainLanguage", "SubpopulationFlag", "IndicatorConditionFlag")
#stresstoind <- c("Stressor" = "Indicator", "StressorPlainLanguage"= "IndicatorPlainLanguage")
stresstoind <- c("Indicator" = "Stressor", "IndicatorPlainLanguage"= "StressorPlainLanguage")
col_suffix <- c("Type", "Subpopulation", "Stressor", "Response")


#///////////////////////////#
#     METADATA TABLES       #
#///////////////////////////#

# Loading reference plain language tables from Excel
setwd(paste(root, "/Reference", sep=""))

reference <- list.files(pattern=c("Reference", "*.xlsx"))


#//////////////////////////#
#     PLAIN LANGUAGE       #
#//////////////////////////#

## Using reference[length(reference)] assumes that the right saving conventions are used (version number increases), so the most recent file would be the last in the list.
pl_indcat <- read_xlsx(reference[length(reference)], sheet="Indicator & Category Combos") %>%
  select(Indicator, IndicatorPlainLanguage, Category, CategoryConditionPlainLanguage, CategoryConditionMostDisturbed, IndicatorConditionFlag)
pl_only_indicator <- select(pl_indcat, Indicator, IndicatorPlainLanguage)

pl_only_stressor <- select(pl_indcat, Stressor = Indicator, StressorPlainLanguage = IndicatorPlainLanguage)

pl_only_category <- select(pl_indcat, Category, CategoryConditionPlainLanguage)

############################

pl_subpoptype <- read_xlsx(reference[length(reference)], sheet="Type & Subpop Combos") %>%
  select(Type, TypePlainLanguage, Subpopulation, SubpopulationPlainLanguage, SubpopulationFlag)

pl_only_subpop <- select(pl_subpoptype, Subpopulation, SubpopulationPlainLanguage)

pl_only_type <- select(pl_subpoptype, Type, TypePlainLanguage)

############################

metric_categories <- read_xlsx(reference[length(reference)], sheet="Indicator & Metric Categories")

############################

pl_merge <- merge(pl_indcat, pl_subpoptype)  %>%
  filter(Type != "All_Sites") %>%
  filter(Indicator != "Acidification") %>% # Removing old Acidification indicator from padding
  left_join(metric_categories, by="IndicatorPlainLanguage") %>%
  unique()

# Filtering out the subpopulations in the padding itself
pl_merge_filtered <- filter(pl_merge, SubpopulationFlag == "Keep")


#/////////////////////////////////#
#           SUBPOP ABBREV         #
#/////////////////////////////////#

#Loading subpop abbreviation names for use in the condition matrix

abbr_subpop <- read_xlsx(reference[length(reference)], sheet="Type & Subpop Combos") %>%
  select(Subpopulation, SubpopulationPlainLanguage, SubpopAbbrev, SubpopulationFlag) %>%
  filter(SubpopulationFlag == "Keep") %>%
  subset(., select = -c(SubpopulationFlag))


setwd(root)
